[WIP] Use docker-compose
misskey-delta/misskey-docker pull request #8
Opened 2018-09-08 12:36 UTC by otofune

#7 

* misskey-storage を使うのはいいのか
* misskey-storage の動作確認取れてない・minio の確認もしてない

2019-01-19 06:42 UTC, rokoucha approved these changes
良いと思った

2019-01-19 20:52 UTC, otofune commented
これ storage まだバグってるんですよ

2019-01-20 05:42 UTC, rokoucha requested changes
じゃあrequest changesします…

2019-02-16 17:42 UTC, rokoucha requested changes
https://travis-ci.org/future-link/misskey-docker/jobs/487666820#L832
Nodeのバージョンを上げたら対応するnode.bcrypt.js v1.0.3のリリースがないためビルドできない。

https://github.com/kelektiv/node.bcrypt.js/releases/tag/v2.0.1
v2.0.1以上に上げないと対応しないっぽい。
困ったね

2019-05-30 04:14 UTC, closed without merging